export const RAW_PRODUCTS = [
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 1000,
        "price": 800.0,
        "tags": [],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 1kg Pack",
        "product_id": "PROD-APRIC-1000",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-1000",
        "barcode": "260341663299"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 6000,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 6kg Pack",
        "product_id": "PROD-ALMON-6000",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-6000",
        "barcode": "978373585305"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 4500,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 4.5kg Pack",
        "product_id": "PROD-CASHE-4500",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-4500",
        "barcode": "115228340788"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 1000,
        "price": 500.0,
        "tags": [],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 1kg Pack",
        "product_id": "PROD-BLACK-1000",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-1000",
        "barcode": "124877423921"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 3000,
        "price": 2000.0,
        "tags": [],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 3kg Pack",
        "product_id": "PROD-CASHE-3000",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-3000",
        "barcode": "115228340788"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 250,
        "price": 300.0,
        "tags": [],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 250g Pack",
        "product_id": "PROD-CASHE-250",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-250",
        "barcode": "115228340788"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 1000,
        "price": 500.0,
        "tags": [],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 1kg Pack",
        "product_id": "PROD-ALMON-1000",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-1000",
        "barcode": "978373585305"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 4000,
        "price": 2000.0,
        "tags": [],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 4kg Pack",
        "product_id": "PROD-BLACK-4000",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-4000",
        "barcode": "124877423921"
    },
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 1500,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 1.5kg Pack",
        "product_id": "PROD-APRIC-1500",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-1500",
        "barcode": "260341663299"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 1000,
        "price": 800.0,
        "tags": [],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 1kg Pack",
        "product_id": "PROD-BRAZI-1000",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-1000",
        "barcode": "090836928289"
    },
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 4500,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 4.5kg Pack",
        "product_id": "PROD-APRIC-4500",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-4500",
        "barcode": "260341663299"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 4000,
        "price": 2000.0,
        "tags": [],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 4kg Pack",
        "product_id": "PROD-ALMON-4000",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-4000",
        "barcode": "978373585305"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 2000,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 2kg Pack",
        "product_id": "PROD-ALMON-2000",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-2000",
        "barcode": "978373585305"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 600,
        "price": 500.0,
        "tags": [],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 600g Pack",
        "product_id": "PROD-BRAZI-600",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-600",
        "barcode": "090836928289"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 1600,
        "price": 800.0,
        "tags": [],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 1.6kg Pack",
        "product_id": "PROD-ALMON-1600",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-1600",
        "barcode": "978373585305"
    },
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 600,
        "price": 500.0,
        "tags": [],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 600g Pack",
        "product_id": "PROD-APRIC-600",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-600",
        "barcode": "260341663299"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 600,
        "price": 500.0,
        "tags": [],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 600g Pack",
        "product_id": "PROD-CHIAS-600",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-600",
        "barcode": "874971923843"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 1500,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 1.5kg Pack",
        "product_id": "PROD-CASHE-1500",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-1500",
        "barcode": "115228340788"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 1000,
        "price": 800.0,
        "tags": [],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 1kg Pack",
        "product_id": "PROD-CHIAS-1000",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-1000",
        "barcode": "874971923843"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 1500,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 1.5kg Pack",
        "product_id": "PROD-BRAZI-1500",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-1500",
        "barcode": "090836928289"
    },
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 250,
        "price": 300.0,
        "tags": [],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 250g Pack",
        "product_id": "PROD-APRIC-250",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-250",
        "barcode": "260341663299"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 4500,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 4.5kg Pack",
        "product_id": "PROD-BRAZI-4500",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-4500",
        "barcode": "090836928289"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 1000,
        "price": 800.0,
        "tags": [],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 1kg Pack",
        "product_id": "PROD-CASHE-1000",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-1000",
        "barcode": "115228340788"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 3000,
        "price": 2000.0,
        "tags": [],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 3kg Pack",
        "product_id": "PROD-CHIAS-3000",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-3000",
        "barcode": "874971923843"
    },
    {
        "name": "Cashews",
        "category": "Common Dry Fruits",
        "weight_g": 600,
        "price": 500.0,
        "tags": [],
        "rating": 3.5,
        "review_count": 3030,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Cashews - 600g Pack",
        "product_id": "PROD-CASHE-600",
        "short_description": "High-quality Cashews packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Cashews comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CASHE-600",
        "barcode": "115228340788"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 1500,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 1.5kg Pack",
        "product_id": "PROD-CHIAS-1500",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-1500",
        "barcode": "874971923843"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 4500,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 4.5kg Pack",
        "product_id": "PROD-CHIAS-4500",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-4500",
        "barcode": "874971923843"
    },
    {
        "name": "Apricots (Khumani)",
        "category": "Common Dry Fruits",
        "weight_g": 3000,
        "price": 2000.0,
        "tags": [],
        "rating": 3.8,
        "review_count": 4537,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Apricots (Khumani) - 3kg Pack",
        "product_id": "PROD-APRIC-3000",
        "short_description": "High-quality Apricots (Khumani) packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Apricots (Khumani) comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "APRIC-3000",
        "barcode": "260341663299"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 600,
        "price": 300.0,
        "tags": [],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 600g Pack",
        "product_id": "PROD-BLACK-600",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-600",
        "barcode": "124877423921"
    },
    {
        "name": "Chia Seeds",
        "category": "Seeds",
        "weight_g": 250,
        "price": 300.0,
        "tags": [],
        "rating": 4.7,
        "review_count": 4100,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Chia Seeds - 250g Pack",
        "product_id": "PROD-CHIAS-250",
        "short_description": "High\u2011quality Chia Seeds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Chia Seeds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Seeds' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "CHIAS-250",
        "barcode": "874971923843"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 3000,
        "price": 2000.0,
        "tags": [],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 3kg Pack",
        "product_id": "PROD-BRAZI-3000",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-3000",
        "barcode": "090836928289"
    },
    {
        "name": "Almonds",
        "category": "Common Dry Fruits",
        "weight_g": 600,
        "price": 300.0,
        "tags": [],
        "rating": 4.6,
        "review_count": 975,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Almonds - 600g Pack",
        "product_id": "PROD-ALMON-600",
        "short_description": "High-quality Almonds packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Almonds comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Common Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "ALMON-600",
        "barcode": "978373585305"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 1600,
        "price": 800.0,
        "tags": [],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 1.6kg Pack",
        "product_id": "PROD-BLACK-1600",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-1600",
        "barcode": "124877423921"
    },
    {
        "name": "Brazil Nuts",
        "category": "Exotic Dry Fruits",
        "weight_g": 250,
        "price": 300.0,
        "tags": [],
        "rating": 3.6,
        "review_count": 98,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Brazil Nuts - 250g Pack",
        "product_id": "PROD-BRAZI-250",
        "short_description": "High-quality Brazil Nuts packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Brazil Nuts comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BRAZI-250",
        "barcode": "090836928289"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 6000,
        "price": 3000.0,
        "tags": [
            "gift wrapped"
        ],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 6kg Pack",
        "product_id": "PROD-BLACK-6000",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-6000",
        "barcode": "124877423921"
    },
    {
        "name": "Black Raisins",
        "category": "Exotic Dry Fruits",
        "weight_g": 2000,
        "price": 1000.0,
        "tags": [
            "best seller"
        ],
        "rating": 4.2,
        "review_count": 4573,
        "image": "https://images.unsplash.com/photo-1670777208596-adcab4ddc8d9?q=80&w=908&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "title": "Black Raisins - 2kg Pack",
        "product_id": "PROD-BLACK-2000",
        "short_description": "High-quality Black Raisins packed fresh for everyday healthy snacking.",
        "long_description": "Our premium Black Raisins comes from trusted farms and suppliers. Perfect for snacking, gifting, cooking, and festive use. This product falls under the 'Exotic Dry Fruits' category and is hygienically packed to retain freshness, taste, and natural nutrition.",
        "stock_status": "in_stock",
        "SKU": "BLACK-2000",
        "barcode": "124877423921"
    }
];